apiVersion: apps/v1
kind: Deployment
# Deployment metadata
metadata:
  name: [microservice]-deployment
  labels:
    app: [microservice]
    environment: local
spec: # Contains the specification of a pod
  replicas: 1
  selector: # Specifies labels that pods need to match to be managed by this deployment
    matchLabels:
      app: [microservice]
      environment: local
  template:
    metadata:
      labels: # Pods labels
        app: [microservice]
        environment: local
    spec:
      containers:
      - name: [microservice]
        image: [microservice]:latest
        imagePullPolicy: Never
