---
title: "Group projects"
date: "9 octobre 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Goals and Instructions

Gather in group of five people, pick a topic and build a data science product with R.

What is a data science project ?

It...

+ extracts data from the web (wikipedia pages, books from [Gutemberg projet](https://www.gutenberg.org/wiki/Gutenberg:Information_About_Robot_Access_to_our_Pages), [open images dataset](https://storage.googleapis.com/openimages/web/download.html)...)

+ ...or collect them via an API (Spotify, Facebook, Twitter, Velib,...)

+ ...or open data (EDF, Enedis, RATP, SNCF in french...Quandl in english)

+ ...or public datasets (https://github.com/caesar0301/awesome-public-datasets, netflix challenge, kaggle, https://www.datascience.net/fr/challenge in french, [open data platform of new york](https://opendata.cityofnewyork.us/data/#datasetscategory), [open data platform of UK](https://data.gov.uk/), [open data platform of the U.S.A](https://www.data.gov/), [open data platform from India](https://data.gov.in/))

+ wisely gather them,

+ tidy them, transform them,

+ explor and manipulate them,

+ vizualize them,

+ build models to predict, cluster, explain... ( [h2o](https://cran.r-project.org/web/packages/h2o/index.html), [keras](https://keras.rstudio.com/)... )

+ share insights, add value, communicate or dashboard them

The project should at least be an R package (with documentation, vignette...). The project must be version controled and hosted on github or git.thinkr.fr: we must be able to see the history of the project through to history of the commits. You must commit-push-pull as often as breathing: commit is the new Ctrl+S. 

Technical R skills will be a major part of your grade.


## Submission 

Send an R package and a link to a github/gitlab repo. If the package is too heavy to be sent by mail, please mention it in the email.

## Schedule

Email to send us the group composition: xhec2018@thinkr.fr

Due date for emailing us the group composition and topic: 2018-10-17

Due date for the project: 2018-12-14

Group defense: 2018-12-17


## Topic suggestions


**Project specifications are  suggestions and  not restrictions — feel free to drop some features and to add others which are not listed here**

### Open Spider

Inspired by products like the SEO spider from screaming frog (https://www.screamingfrog.co.uk/seo-spider/), build a website crawler that would go on a website and return informations about the website. These information can be: content of the page, list of headers and their content, depth of the page from the home url (number of link to follow before getting to this page), number of words, number of images, number of internal and external links, sentiment analysis of the content... Anything that could help someone analysing the content of a website"

### Tweetboard

Create a dashboard that allow users to analyse tweets for a given hashtag.
In this dashboard, you might find: most active users, emoji analyses, timeline, word frequency, sentiment analysis, relationships between users...

### Find my bus - Real-time analysis of buses position from Rennes city

Based on the API from Star Open Data https://data.explore.star.fr/page/home/ and any other open data you might find useful, build a navigation interface that allows the user to navigate in Rennes. This app can include, for example: position of the bus in real time, an interface to get the name of the next bus for a given spot, creation of routes from one spot in the city to another, real time alert... Be creative, you can also include a city guide if you wish."
https://data.explore.star.fr/api/v1/console/datasets/1.0/search/

### Easy Google analytics

Google analytics default dashboard is a mess if you're not an experimented user: lots of tabs and data which are not that easy to understand. Build a dashboard which makes analysing Google Analytics data more user-friendly. This dashboard should be simpler to use, yet provides key features from the website data. If you feel inspired, feel free to pimp this dashboard (for example, by making prediction about future number of visits...)


### Bechdel test, again.

Gather into a package data from Bechdeltest.com, submit it to CRAN and set up a process to update the data on a weekly basis. Build an app upon those data to highlight some findings. Feel free to add any other relevant source of data for this purpose. 

### Level of equipment and services in France

[Evolution of the number of equipment and services between 2012 and 2017](https://www.insee.fr/fr/statistiques/3606476?sommaire=3568656) in France cross-referenced to [demographics](https://www.insee.fr/fr/statistiques/2386737). Build a tool to drive public policies by tracking under-equipment

### Semantic analysis

Build an app that provides semantic similarities for the legal vocabulary employed in the French laws (use the LEGI database). The app has to provide access to different models and let the user choose hyperparameters.

### Recommandation engine

Build a recommandation engine for CRAN packages : imagine relevant metrics to mesure popularity, quality, accuracy... according to keywords provided by the user

### What do french/european people eat ? 

Use food consumption survey to describe what french people eat, make links between food supply and health, monitor deficiencies or excess to drive public policies...
INCA2 is a dataset that records every single food intake of 3000+ adults during 7 days : 
https://www.data.gouv.fr/fr/datasets/donnees-de-consommations-et-habitudes-alimentaires-de-letude-inca-2-3/

or, what european people eat ?

Same idea on aggregated data: Can we see differences in diet ? 
https://data.europa.eu/euodp/data/dataset/the-efsa-comprehensive-european-food-consumption-database

### Missing values

Review the existing packages dealing with missing values (visualisation and imputation). Build a tool to compare several approaches and aftermath of missing values imputations.


